package edu.tcu.cs.hogwartsartifactsonline.client.ai.chat.dto;

/**
 * The Choice record encapsulates a Message that represents the output text generated by the AI model from a single prompt.
 * By default, the AI model will only return one choice.
 *
 * @param index
 * @param message
 */
public record Choice(int index,
                     Message message) {
}
